name: Auto Commit
on:
  schedule:
    # Run 3 times per day
    - cron: '0 9 * * *'    # 10:00 Morocco time
    - cron: '0 13 * * *'   # 14:00 Morocco time
    - cron: '0 17 * * *'   # 18:00 Morocco time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --local user.email "saad.derkaoui04@gmail.com"
          git config --local user.name "Saad-Derkaoui"

      - name: Make human-like commits
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=short 2>/dev/null || echo "1970-01-01")
          TODAY=$(date +%Y-%m-%d)

          if [ "$LAST_COMMIT_DATE" = "$TODAY" ]; then
            echo "Already committed today, skipping..."
            exit 0
          fi

          # 50% chance to skip this run
          SHOULD_COMMIT=$((RANDOM % 100))
          if [ $SHOULD_COMMIT -ge 50 ]; then
            echo "Skipping this window..."
            exit 0
          fi

          # Random small number of commits for realism
          NUM_COMMITS=$((1 + RANDOM % 5))
          echo "Making $NUM_COMMITS commits today..."

          for i in $(seq 1 $NUM_COMMITS); do
            echo "Commit #$i - $(date)" >> log.txt
            git add log.txt
            git commit -m "Auto update #$i - $(date +%Y-%m-%d)"

            # Random short delay (3-8 seconds) to simulate human pace
            if [ $i -lt $NUM_COMMITS ]; then
              DELAY=$((3 + RANDOM % 6))
              sleep $DELAY
            fi
          done

          git push
