name: Auto Commit (daily)

on:
  schedule:
    # Run once per day: ~10:00 Morocco time (Africa/Casablanca UTC+1) => 09:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # we'll use PAT for push to attribute to you

      - name: Setup git user
        run: |
          git config --global user.email "saad.derkaoui04@gmail.com"
          git config --global user.name "Saad-Derkaoui"

      - name: Ensure on default branch
        run: |
          # Detect current default branch (main or master)
          if git show-ref --quiet refs/heads/main; then
            BRANCH="main"
          elif git show-ref --quiet refs/heads/master; then
            BRANCH="master"
          else
            echo "No main/master branch found, defaulting to main."
            BRANCH="main"
          fi
          echo "Using branch: $BRANCH"
          git checkout $BRANCH || git checkout -b $BRANCH

      - name: Commit if not already today
        run: |
          set -e
          LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=short 2>/dev/null || echo "1970-01-01")
          TODAY=$(date +%Y-%m-%d)
          if [ "$LAST_COMMIT_DATE" = "$TODAY" ]; then
            echo "Already committed today, skipping."
            exit 0
          fi

          # Random skip chance (optional)
          SHOULD_COMMIT=$((RANDOM % 100))
          if [ $SHOULD_COMMIT -ge 90 ]; then
            echo "Random skip this day."
            exit 0
          fi

          # Make 1–3 commits
          NUM_COMMITS=$((1 + RANDOM % 3))
          for i in $(seq 1 $NUM_COMMITS); do
            echo "Auto commit #$i - $(date -u)" >> .auto-commit-log.txt
            git add .auto-commit-log.txt
            git commit -m "Auto commit #$i - $(date +%Y-%m-%d)"
            if [ $i -lt $NUM_COMMITS ]; then
              sleep $((2 + RANDOM % 5))
            fi
          done

      - name: Push using PAT
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          if [ -z "$PAT" ]; then
            echo "PAT_TOKEN not set — cannot push as your user. Exiting."
            exit 1
          fi
          git remote set-url origin "https://$PAT@github.com/$REPO.git"
          git push origin HEAD
